const MAKE_OPTIONS = {
  categories: [
    {
      id: "shape",
      label: "Shape",
      options: [
        "Blob",
        "Round",
        "Pear",
        "Tall",
        "Squat",
        "Bean",
        "Furry Ball",
        "Potato",
        "Triangle-ish",
        "Lumpy",
        "Egg-shaped",
        "Wide",
        "Tiny Body / Big Head",
        "Big Body / Tiny Head",
      ],
    },
    {
      id: "face",
      label: "Face",
      options: [
        "One Giant Eye",
        "Two Huge Eyes",
        "Tiny Eyes",
        "Three Eyes",
        "Wide-Set Eyes",
        "Googly Mismatched Eyes",
        "Eyes on Stalks",
        "Sleepy Eyes",
        "Beady Eyes",
        "One Eye Bigger Than the Other",
        "No Visible Eyes",
        "Eyes Hidden Under Hair",
      ],
    },
    {
      id: "monsterFeature",
      label: "Monster Feature",
      options: [
        "Horns",
        "Fangs",
        "Giant Ears",
        "Antennae",
        "Tufts of Hair",
        "Spikes",
        "Long Tail",
        "Tiny Wings",
        "Big Mouth",
        "Underbite",
        "Pointy Teeth",
        "Fuzzy Fur",
        "Long Arms",
        "Tiny Arms",
        "Long Legs",
        "Tiny Legs",
        "Claws",
        "Bat Ears",
        "Curly Horns",
        "Droopy Ears",
      ],
    },
    {
      id: "exaggerate",
      label: "Exaggerate",
      options: [
        "Eyes",
        "Head",
        "Body",
        "Height",
        "Width",
        "Teeth",
        "Ears",
        "Hair",
        "Arms",
        "Legs",
        "Mouth",
        "Horns",
      ],
    },
    {
      id: "personality",
      label: "Personality",
      options: [
        "Nervous",
        "Grumpy",
        "Delighted",
        "Suspicious",
        "Shy",
        "Mischievous",
        "Confused",
        "Proud",
        "Sleepy",
        "Startled",
        "Curious",
        "Cranky",
        "Sweet",
        "Goofy",
        "Sneaky",
      ],
    },
  ],
};
