const MAKE_OPTIONS = {
  categories: [
    {
      id: "shape",
      label: "Body Shape",
      options: [
        "Blob",
        "Round",
        "Pear",
        "Tall",
        "Squat",
        "Bean",
        "Furry Ball",
        "Potato",
        "Triangle-ish",
        "Lumpy",
        "Egg-shaped",
        "Wide",
        "Tiny Body / Big Head",
        "Big Body / Tiny Head",
      ],
    },
    {
      id: "face",
      label: "Face",
      options: [
        "Two huge round eyes + stitched mouth",
        "One enormous eye + tiny crooked smile",
        "Three tiny eyes + wide toothy grin",
        "Uneven button eyes + little fanged mouth",
        "Hollow black eyes + tiny O-shaped mouth",
        "One sleepy eye + crooked buck-toothed grin",
        "Two close-set eyes + long zipper mouth",
        "Tiny dot eyes + enormous jagged smile",
        "One large eye and one tiny eye + nervous squiggly mouth",
        "Two droopy eyes + two little fangs",
        "Wide-set eyes + crooked frown",
        "Mismatched googly eyes + very wide smile",
        "Eyes on stalks + tiny smile",
        "Beady eyes + jagged grin",
        "One huge eye + zipper mouth",
        "Three sleepy eyes + squiggly nervous mouth",
        "Button eyes + crooked smile",
        "Two tiny eyes + buck teeth",
        "One big eye and one tiny eye + stitched mouth",
        "Hollow black eyes + toothy grin",
      ],
    },
    {
      id: "oddity",
      label: "Oddity",
      options: [
        "Horns",
        "Antennae",
        "Pointy ears",
        "Bat wings",
        "Tiny wings",
        "Tufts of Hair",
        "Spikes",
        "Bolts",
        "Exposed bones",
        "Patchwork skin",
        "Tentacles",
        "Long claws",
        "Extra eye",
        "Floppy ears",
        "Leafy or vine growth",
        "Hay sticking out",
        "Ghostly wisps",
        "Stripes",
        "Spots",
        "Upside-down head",
        "Floating hands",
        "Extra-long fingers",
        "Mismatched arms",
        "Transparent belly",
        "Backwards feet",
        "Detachable head",
        "Holes through the body",
        "Stitched together",
        "Something growing out of it",
      ],
    },
    {
      id: "exaggerate",
      label: "Exaggerate",
      options: [
        "Eyes",
        "Head",
        "Height",
        "Arms",
        "Legs",
        "Hair",
        "Teeth",
        "Ears",
      ],
    },
  ],
};
