const MONSTER_CATEGORIES = [
  {
    id: "monsterType",
    label: "Monster Type",
    resultLabel: "Monster Type",
    options: [
      "Monster",
      "Vampire",
      "Zombie",
      "Mummy",
      "Witch",
      "Ghost",
      "Skeleton",
      "Pumpkin",
      "Bat",
      "Spider",
      "Werewolf",
      "Stitched Monster",
      "Swamp Monster",
      "Goblin",
    ],
  },
  {
    id: "headShape",
    label: "Head Shape",
    resultLabel: "Head",
    options: [
      "Circle",
      "Oval",
      "Square",
      "Rectangle",
      "Triangle",
      "Teardrop",
      "Gumdrop",
      "Bean",
      "Egg",
      "Mushroom",
      "Crescent",
      "Blob",
    ],
  },
  {
    id: "bodyShape",
    label: "Body Shape",
    resultLabel: "Body",
    options: [
      "Circle",
      "Oval",
      "Square",
      "Rectangle",
      "Triangle",
      "Teardrop",
      "Gumdrop",
      "Bean",
      "Egg",
      "Blob",
    ],
  },
  {
    id: "numberOfEyes",
    label: "Number of Eyes",
    resultLabel: "Eyes",
    options: ["1", "2", "3", "4", "5", "6", "Many"],
  },
  {
    id: "eyeShape",
    label: "Eye Shape",
    resultLabel: "Eye Shape",
    options: [
      "Dot",
      "Circle",
      "Oval",
      "Gumdrop",
      "Teardrop",
      "Almond",
      "Googly",
      "Beady",
      "Giant Round",
      "Sleepy / Half-Moon",
    ],
  },
  {
    id: "mouth",
    label: "Mouth",
    resultLabel: "Mouth",
    options: [
      "No Mouth",
      "Tiny Mouth",
      "Big Mouth",
      "Toothy",
      "Fangs",
      "One Tooth",
      "Two Teeth",
      "Jagged Teeth",
      "O-Shaped",
      "Crooked",
      "Underbite",
      "Tongue Sticking Out",
    ],
  },
  {
    id: "headExtra",
    label: "Head Extra",
    resultLabel: "Head Extra",
    options: [
      "Nothing",
      "1 Horn",
      "2 Horns",
      "Antennae",
      "Eyeball Stalks",
      "Pointy Ears",
      "Bat Ears",
      "Floppy Ears",
      "Tiny Ears",
      "Tuft of Hair",
      "Wild Hair",
      "Mohawk",
      "Witch Hat",
      "Tiny Hat",
      "Top Hat",
      "Skull Cap",
      "Pumpkin Stem",
      "Bones",
      "Skull",
      "Spider Friend",
      "Mushroom",
      "Crown",
    ],
  },
  {
    id: "numberOfArms",
    label: "Number of Arms",
    resultLabel: "Arms",
    options: ["0", "2", "4", "6", "8"],
  },
  {
    id: "armShape",
    label: "Arm Shape",
    resultLabel: "Arm Shape",
    options: [
      "Long + Skinny",
      "Short + Skinny",
      "Long + Fat",
      "Short + Fat",
      "Curvy",
      "Tentacle",
    ],
  },
  {
    id: "numberOfLegs",
    label: "Number of Legs",
    resultLabel: "Legs",
    options: ["0", "1", "2", "3", "4", "6", "8"],
  },
  {
    id: "legShape",
    label: "Leg Shape",
    resultLabel: "Leg Shape",
    options: [
      "Long + Skinny",
      "Short + Skinny",
      "Long + Fat",
      "Short + Fat",
      "Curvy",
      "Tentacle",
    ],
  },
  {
    id: "tail",
    label: "Tail",
    resultLabel: "Tail",
    options: [
      "No Tail",
      "Tiny Tail",
      "Long Tail",
      "Curly Tail",
      "Pointy Tail",
      "Fuzzy Tail",
      "Devil Tail",
      "Dinosaur Tail",
    ],
  },
  {
    id: "texture",
    label: "Texture",
    resultLabel: "Texture",
    options: [
      "Smooth",
      "Furry",
      "Fuzzy",
      "Hairy",
      "Bumpy",
      "Warty",
      "Scaly",
      "Slimy",
      "Wrinkly",
      "Stitched",
      "Patchy",
      "Striped",
      "Spotted",
    ],
  },
];

const MAYHEM_CATEGORY = {
  id: "spookyThing",
  label: "Spooky Thing",
  resultLabel: "Spooky Thing",
  options: [
    "Eyeball",
    "Haunted House",
    "Coffin",
    "Gravestone",
    "Cauldron",
    "Potion",
    "Broom",
    "Black Cat",
    "Spiderweb",
    "Spider",
    "Bat",
    "Ghost",
    "Pumpkin",
    "Jack-o'-Lantern",
    "Skull",
    "Bone",
    "Skeleton",
    "Brain",
    "Brain in a Jar",
    "Candle",
    "Candy Bucket",
    "Candy Corn",
    "Witch Hat",
    "Vampire Teeth",
    "Skeleton Key",
    "Mysterious Door",
    "Old Portrait",
    "Spell Book",
    "Crystal Ball",
    "Poison Apple",
    "Raven",
    "Moon",
    "Mushroom",
  ],
};
