const MONSTER_CATEGORIES = [
  {
    id: "headShape",
    label: "Head Shape",
    resultLabel: "Head",
    options: [
      "No Separate Head",
      "Circle",
      "Oval",
      "Square",
      "Rectangle",
      "Teardrop",
      "Gumdrop",
      "Egg",
      "Blob",
    ],
  },
  {
    id: "bodyShape",
    label: "Body Shape",
    resultLabel: "Body",
    options: [
      "Circle",
      "Oval",
      "Square",
      "Rectangle",
      "Triangle",
      "Teardrop",
      "Gumdrop",
      "Bean",
      "Egg",
      "Blob",
    ],
  },
  {
    id: "numberOfEyes",
    label: "Number of Eyes",
    resultLabel: "Eyes",
    options: ["1", "2", "3", "4", "5", "6", "Many"],
  },
  {
    id: "eyeShape",
    label: "Eye Shape",
    resultLabel: "Eye Shape",
    options: [
      "Dot",
      "Circle",
      "Oval",
      "Gumdrop",
      "Teardrop",
      "Almond",
      "Googly",
      "Beady",
      "Giant Round",
      "Sleepy / Half-Moon",
    ],
  },
  {
    id: "mouth",
    label: "Mouth",
    resultLabel: "Mouth",
    options: [
      "No Mouth",
      "Tiny Mouth",
      "Big Mouth",
      "Toothy",
      "Fangs",
      "One Tooth",
      "Two Teeth",
      "Jagged Teeth",
      "O-Shaped",
      "Crooked",
      "Underbite",
      "Tongue Sticking Out",
    ],
  },
  {
    id: "monsterFeature",
    label: "Monster Feature",
    resultLabel: "Monster Feature",
    options: [
      "Nothing",
      "1 Horn",
      "2 Horns",
      "Antennae",
      "Eyeball Stalks",
      "Witch Hat",
      "Tiny Hat",
      "Top Hat",
      "Bat Wings",
      "Tiny Wings",
      "Tuft of Hair",
      "Wild Hair",
      "Mohawk",
      "Pumpkin Stem",
      "Bones",
      "Spider Friend",
      "Mushroom",
      "Crown",
    ],
  },
  {
    id: "texture",
    label: "Texture",
    resultLabel: "Texture",
    options: [
      "Smooth",
      "Furry",
      "Fuzzy",
      "Hairy",
      "Bumpy",
      "Warty",
      "Scaly",
      "Slimy",
      "Wrinkly",
      "Stitched",
      "Patchy",
      "Striped",
      "Spotted",
    ],
  },
  {
    id: "numberOfArms",
    label: "Number of Arms",
    resultLabel: "Arms",
    options: ["0", "2", "4", "6"],
  },
  {
    id: "armShape",
    label: "Arm Shape",
    resultLabel: "Arm Shape",
    options: [
      "Long + Skinny",
      "Short + Skinny",
      "Long + Fat",
      "Short + Fat",
      "Curvy",
      "Tentacle",
    ],
  },
  {
    id: "numberOfLegs",
    label: "Number of Legs",
    resultLabel: "Legs",
    options: ["0", "1", "2", "3", "4"],
  },
  {
    id: "legShape",
    label: "Leg Shape",
    resultLabel: "Leg Shape",
    options: [
      "Long + Skinny",
      "Short + Skinny",
      "Long + Fat",
      "Short + Fat",
      "Curvy",
      "Tentacle",
    ],
  },
  {
    id: "tail",
    label: "Tail",
    resultLabel: "Tail",
    options: [
      "No Tail",
      "Tiny Tail",
      "Long Tail",
      "Curly Tail",
      "Pointy Tail",
      "Fuzzy Tail",
      "Devil Tail",
      "Dinosaur Tail",
    ],
  },
];

const MAYHEM_CATEGORY = {
  id: "spookyThing",
  label: "Spooky Thing",
  resultLabel: "Spooky Thing",
  options: [
    "Eyeball",
    "Haunted House",
    "Coffin",
    "Gravestone",
    "Cauldron",
    "Potion",
    "Broom",
    "Black Cat",
    "Spiderweb",
    "Spider",
    "Bat",
    "Ghost",
    "Pumpkin",
    "Jack-o'-Lantern",
    "Skull",
    "Bone",
    "Skeleton",
    "Brain",
    "Brain in a Jar",
    "Candle",
    "Candy Bucket",
    "Candy Corn",
    "Witch Hat",
    "Vampire Teeth",
    "Skeleton Key",
    "Mysterious Door",
    "Old Portrait",
    "Spell Book",
    "Crystal Ball",
    "Poison Apple",
    "Raven",
    "Moon",
    "Mushroom",
  ],
};
